<a href="https://colab.research.google.com/github/domelmel/colab/blob/main/lerarn_torch_00.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.0.1+cu118


In [ ]:
!nvidia-smi

Mon Sep 18 12:43:09 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.105.17   Driver Version: 525.105.17   CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   35C    P8     9W /  70W |      0MiB / 15360MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [ ]:
#scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
scalar.ndim

0

In [ ]:
#GEt tensor back as Python int
scalar.item()

7

In [ ]:
#Vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [ ]:
vector.ndim

1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
#MATRIX
MATRIX = torch.tensor([[7,8],
                       [9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [ ]:
MATRIX.ndim

2

In [ ]:
MATRIX[1]

tensor([ 9, 10])

In [ ]:
MATRIX.shape

torch.Size([2, 2])

In [ ]:
#TENSOR
TENSOR = torch.tensor([[[1,2,3],[3,4,5],[2,4,5]]])
TENSOR


tensor([[[1, 2, 3],
         [3, 4, 5],
         [2, 4, 5]]])

In [ ]:
TENSOR.ndim


3

In [ ]:
TENSOR.shape

torch.Size([1, 3, 3])

In [ ]:
import torch
from torch import nn
from torch.utils.data import DataLoader
from torchvision import datasets
from torchvision.transforms import ToTensor
# Download training data from open datasets.
training_data = datasets.FashionMNIST(
    root="data",
    train=True,
    download=True,
    transform=ToTensor(),
)

# Download test data from open datasets.
test_data = datasets.FashionMNIST(
    root="data",
    train=False,
    download=True,
    transform=ToTensor(),
)



100%|██████████| 26421880/26421880 [00:02<00:00, 12382750.78it/s]


Extracting data/FashionMNIST/raw/train-images-idx3-ubyte.gz to data/FashionMNIST/raw



100%|██████████| 29515/29515 [00:00<00:00, 225858.97it/s]


Extracting data/FashionMNIST/raw/train-labels-idx1-ubyte.gz to data/FashionMNIST/raw



100%|██████████| 4422102/4422102 [00:01<00:00, 3906681.02it/s]


Extracting data/FashionMNIST/raw/t10k-images-idx3-ubyte.gz to data/FashionMNIST/raw



100%|██████████| 5148/5148 [00:00<00:00, 6240542.48it/s]

Extracting data/FashionMNIST/raw/t10k-labels-idx1-ubyte.gz to data/FashionMNIST/raw



In [ ]:
batch_size = 64

# Create data loaders.
train_dataloader = DataLoader(training_data, batch_size=batch_size)
test_dataloader = DataLoader(test_data, batch_size=batch_size)

for X, y in test_dataloader:
    print(f"Shape of X [N, C, H, W]: {X.shape}")
    print(f"Shape of y: {y.shape} {y.dtype}")
    break

Shape of X [N, C, H, W]: torch.Size([64, 1, 28, 28])
Shape of y: torch.Size([64]) torch.int64


In [ ]:
# Get cpu, gpu or mps device for training.
device = (
    "cuda"
    if torch.cuda.is_available()
    else "mps"
    if torch.backends.mps.is_available()
    else "cpu"
)
print(f"Using {device} device")

# Define model
class NeuralNetwork(nn.Module):
    def __init__(self):
        super().__init__()
        self.flatten = nn.Flatten()
        self.linear_relu_stack = nn.Sequential(
            nn.Linear(28*28, 512),
            nn.ReLU(),
            nn.Linear(512, 512),
            nn.ReLU(),
            nn.Linear(512, 10)
        )

    def forward(self, x):
        x = self.flatten(x)
        logits = self.linear_relu_stack(x)
        return logits

model = NeuralNetwork().to(device)
print(model)

Using cpu device
NeuralNetwork(
  (flatten): Flatten(start_dim=1, end_dim=-1)
  (linear_relu_stack): Sequential(
    (0): Linear(in_features=784, out_features=512, bias=True)
    (1): ReLU()
    (2): Linear(in_features=512, out_features=512, bias=True)
    (3): ReLU()
    (4): Linear(in_features=512, out_features=10, bias=True)
  )
)


In [ ]:
import torch

# Create two random tensors
random_tensor_A = torch.rand(3, 4,5)
print(random_tensor_A.ndim)

3


In [ ]:
print(f"Tensor A:\n{random_tensor_A}\n")

Tensor A:
tensor([[[0.5901, 0.0963, 0.3109, 0.4065, 0.7120],
         [0.9572, 0.0097, 0.8790, 0.3316, 0.4428],
         [0.9785, 0.6677, 0.4178, 0.4293, 0.5901],
         [0.7913, 0.4319, 0.8271, 0.8121, 0.6009]],

        [[0.8619, 0.3266, 0.3880, 0.1746, 0.7131],
         [0.3607, 0.7000, 0.6500, 0.4085, 0.4266],
         [0.5665, 0.4255, 0.8847, 0.6472, 0.3118],
         [0.2403, 0.6041, 0.1068, 0.7405, 0.3368]],

        [[0.0760, 0.1688, 0.7918, 0.9106, 0.2386],
         [0.8704, 0.7890, 0.6174, 0.1071, 0.3225],
         [0.0478, 0.4949, 0.3256, 0.1694, 0.8721],
         [0.2335, 0.1311, 0.4053, 0.1867, 0.3746]]])



In [ ]:


!nvidia-smi


Mon Sep 18 12:43:04 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.105.17   Driver Version: 525.105.17   CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   35C    P8     9W /  70W |      0MiB / 15360MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [ ]:
# Check for GPU
import torch
torch.cuda.is_available()

True

In [ ]:
# Set device type
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [ ]:


# Count number of devices
torch.cuda.device_count()


1

In [ ]:
# Create tensor (default on CPU)
tensor = torch.tensor([1, 2, 3])

# Tensor not on GPU
print(tensor, tensor.device)

# Move tensor to GPU (if available)
tensor_on_gpu = tensor.to(device)
tensor_on_gpu


tensor([1, 2, 3]) cpu


tensor([1, 2, 3], device='cuda:0')

In [ ]:
# If tensor is on GPU, can't transform it to NumPy (this will error)
tensor_on_gpu.numpy()

TypeError: ignored

# New Section

In [ ]:
# Instead, copy the tensor back to cpu
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])

In [ ]:


tensor_on_gpu


tensor([1, 2, 3], device='cuda:0')

In [5]:
import torch

random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.5865, 0.7369, 0.9458, 0.2362],
        [0.2578, 0.0726, 0.5551, 0.7575],
        [0.2077, 0.8164, 0.3556, 0.7705]])

In [6]:
random_tensor.ndim

2

In [9]:
random_image_size_tensor = torch.rand(size=(3,224,224))
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

In [10]:
random_image_size_tensor


tensor([[[5.9416e-02, 3.9276e-01, 2.6601e-02,  ..., 3.3983e-01,
          3.0441e-01, 3.2642e-01],
         [8.0270e-01, 6.4078e-01, 7.9988e-01,  ..., 6.5324e-01,
          6.8350e-01, 4.8749e-01],
         [1.4568e-01, 9.7350e-01, 5.2600e-01,  ..., 4.2487e-01,
          8.2205e-01, 9.4508e-01],
         ...,
         [4.3824e-01, 8.3485e-01, 6.1889e-01,  ..., 3.8157e-01,
          8.9814e-01, 3.7373e-01],
         [8.8920e-01, 6.3946e-01, 6.0695e-01,  ..., 8.8390e-01,
          9.0190e-01, 6.7242e-01],
         [8.4183e-01, 3.2408e-01, 3.6540e-01,  ..., 3.7285e-01,
          1.2390e-01, 6.2901e-01]],

        [[2.8832e-01, 2.0295e-01, 1.9428e-01,  ..., 8.5757e-01,
          8.3994e-01, 3.8568e-01],
         [5.4962e-01, 2.0969e-01, 2.0239e-01,  ..., 4.8100e-01,
          4.4108e-01, 7.7998e-01],
         [8.2348e-01, 5.9496e-01, 3.1659e-01,  ..., 2.6880e-01,
          1.0835e-01, 7.6971e-01],
         ...,
         [6.1122e-01, 6.9646e-02, 4.2583e-01,  ..., 2.2697e-01,
          6.238

In [11]:
torch.rand(3,3)

tensor([[0.4391, 0.1463, 0.6634],
        [0.3767, 0.4253, 0.0172],
        [0.4637, 0.5125, 0.9749]])

In [15]:
zeros = torch.zeros(3,3)
zeros


tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [16]:
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [17]:
ones.dtype

torch.float32

In [19]:
torch.__version__

'2.0.1+cu118'

In [27]:
one_to_ten= torch.arange(start=0,end=11,step=1)
one_to_ten

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [30]:
ten_zeros =torch.zeros_like(one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [34]:
ten_zeros.shape

torch.Size([11])

In [3]:
import torch
f32tensor = torch.tensor([3.0,6.0,9.0],dtype=None)
f32tensor.dtype

torch.float32

In [5]:
f16tensor = f32tensor.type(torch.float16)
f16tensor

tensor([3., 6., 9.], dtype=torch.float16)